const { expect } = require("chai");
const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

// PARITY -- the critical test for NANDFLY Task 3: NandFly.sol's swat() must agree
// with circuit/gates.py (the reference evaluator) on ALL 4096 possible 12-bit
// stimulus patterns. No sampling. The fixture (contract/fixtures/parity_4096.json)
// is generated by contract/gen_parity_fixture.py, which calls circuit/gates.py's
// own evaluate_netlist() -- it is a genuine independent oracle, not a
// reimplementation that could share a bug with the Solidity port.
describe("NandFly parity (all 4096 stimulus patterns)", function () {
  it("swat() matches circuit/gates.py for every one of 4096 patterns", async function () {
    const fixturePath = path.join(__dirname, "..", "fixtures", "parity_4096.json");
    const fixture = JSON.parse(fs.readFileSync(fixturePath, "utf-8"));
    expect(fixture.num_patterns).to.equal(4096);
    expect(fixture.results.length).to.equal(4096);

    const NandFly = await ethers.getContractFactory("NandFly");
    const nandfly = await NandFly.deploy();
    await nandfly.waitForDeployment();

    const CHUNK = 128; // batch to keep this test's wall-clock time reasonable;
    // coverage is still all 4096, none sampled/skipped.
    let mismatches = [];
    let checked = 0;

    for (let start = 0; start < fixture.results.length; start += CHUNK) {
      const chunk = fixture.results.slice(start, start + CHUNK);
      const calls = chunk.map((row) => nandfly.swat(row.stimulus));
      const outcomes = await Promise.all(calls);
      for (let i = 0; i < chunk.length; i++) {
        const row = chunk[i];
        const [jumped, jumpLeft, jumpRight] = outcomes[i];
        checked += 1;
        if (
          jumped !== row.jumped ||
          jumpLeft !== row.jumpLeft ||
          jumpRight !== row.jumpRight
        ) {
          mismatches.push({
            stimulus: row.stimulus,
            expected: row,
            got: { jumped, jumpLeft, jumpRight },
          });
        }
      }
    }

    expect(checked).to.equal(4096);
    if (mismatches.length > 0) {
      console.log(`First mismatches (of ${mismatches.length}):`, mismatches.slice(0, 10));
    }
    expect(mismatches.length, `${mismatches.length}/4096 mismatches`).to.equal(0);
  });
});
